/**
 * Content of the two wrapper scripts the installer writes into <home>/hooks/. The agents call the
 * wrapper (never node directly) so the runtime path is pinned at install time and the same
 * settings entry works whether the runtime is `node` or VS Code's own executable.
 */
export interface WrapperInput {
  /** Absolute path of the Node runtime (node binary or VS Code's electron executable). */
  runtime: string;
  /** Absolute path of hooks/explainit-hook.js inside <home>/hooks. */
  script: string;
  /** True when `runtime` is VS Code's own executable (needs ELECTRON_RUN_AS_NODE=1). */
  electron: boolean;
}

/** Double-quoted POSIX shell string: escapes \ " $ and backtick. */
export function shQuote(s: string): string {
  return '"' + s.replace(/[\\"$`]/g, (c) => '\\' + c) + '"';
}

/** Windows cmd argument: wrap in quotes; embedded quotes are not allowed in paths on Windows anyway. */
export function cmdQuote(s: string): string {
  return '"' + s.replace(/"/g, '') + '"';
}

export function wrapperShContent(i: WrapperInput): string {
  const lines = [
    '#!/bin/sh',
    '# ExplainIT checkpoint hook wrapper. Generated by ExplainIT; do not edit (the Doctor rewrites it).',
    '# Runs the hook script with the Node runtime found when ExplainIT was set up.',
  ];
  if (i.electron) {
    lines.push('ELECTRON_RUN_AS_NODE=1');
    lines.push('export ELECTRON_RUN_AS_NODE');
  }
  lines.push(`exec ${shQuote(i.runtime)} ${shQuote(i.script)} "$@"`);
  return lines.join('\n') + '\n';
}

export function wrapperCmdContent(i: WrapperInput): string {
  const lines = ['@echo off', 'rem ExplainIT checkpoint hook wrapper. Generated by ExplainIT; do not edit (the Doctor rewrites it).'];
  if (i.electron) lines.push('set ELECTRON_RUN_AS_NODE=1');
  lines.push(`${cmdQuote(i.runtime)} ${cmdQuote(i.script)} %*`);
  return lines.join('\r\n') + '\r\n';
}

export const WRAPPER_SH = 'explainit-hook.sh';
export const WRAPPER_CMD = 'explainit-hook.cmd';
export const HOOK_SCRIPT = 'explainit-hook.js';

/** Which wrapper the agent config should call on this platform. */
export function wrapperNameFor(platform: NodeJS.Platform): string {
  return platform === 'win32' ? WRAPPER_CMD : WRAPPER_SH;
}
