/**
 * Content of the two wrapper scripts the installer writes into <home>/hooks/. The agents call the
 * wrapper (never node directly) so the runtime path is pinned at install time and the same
 * settings entry works whether the runtime is `node` or VS Code's own executable.
 */
export interface WrapperInput {
  /** Absolute path of the Node runtime (node binary or VS Code's electron executable). */
  runtime: string;
  /** Absolute path of hooks/explainit-hook.js inside <home>/hooks. */
  script: string;
  /** True when `runtime` is VS Code's own executable (needs ELECTRON_RUN_AS_NODE=1). */
  electron: boolean;
  /**
   * Absolute ExplainIT home the wrapper pins into `EXPLAINIT_HOME` before it runs the script, so a
   * shell profile (or an assistant that edited one) cannot point the hook at a rogue sessions folder.
   */
  explainitHome: string;
}

/** Double-quoted POSIX shell string: escapes \ " $ and backtick. */
export function shQuote(s: string): string {
  return '"' + s.replace(/[\\"$`]/g, (c) => '\\' + c) + '"';
}

/** Windows cmd argument: wrap in quotes; embedded quotes are not allowed in paths on Windows anyway. */
export function cmdQuote(s: string): string {
  return '"' + s.replace(/"/g, '') + '"';
}

/**
 * How a path is spelled inside the POSIX wrapper. On Windows the `.sh` wrapper is what Git Bash /
 * MSYS runs, and there a backslash is an escape character, not a separator: `"C:\Users\me"` would
 * reach the hook as `C:Usersme`. Node, cmd.exe and the Windows APIs all accept forward slashes, so
 * drive paths (`C:\x`) and UNC paths (`\\srv\share`) are written with `/`. A POSIX path is left
 * exactly as it is, because there a backslash is a legal character in a file name.
 */
export function shPath(p: string): string {
  return /^[a-zA-Z]:[\\/]/.test(p) || p.startsWith('\\\\') ? p.replace(/\\/g, '/') : p;
}

export function wrapperShContent(i: WrapperInput): string {
  const lines = [
    '#!/bin/sh',
    '# ExplainIT checkpoint hook wrapper. Generated by ExplainIT; do not edit (the Doctor rewrites it).',
    '# Runs the hook script with the Node runtime found when ExplainIT was set up.',
  ];
  if (i.electron) {
    lines.push('ELECTRON_RUN_AS_NODE=1');
    lines.push('export ELECTRON_RUN_AS_NODE');
  }
  // Pinned at install time: whatever the calling shell exported is overridden here. Paths are
  // written in the POSIX spelling because /bin/sh (Git Bash on Windows) reads backslashes as escapes.
  lines.push(`EXPLAINIT_HOME=${shQuote(shPath(i.explainitHome))}`);
  lines.push('export EXPLAINIT_HOME');
  lines.push(`exec ${shQuote(shPath(i.runtime))} ${shQuote(shPath(i.script))} "$@"`);
  return lines.join('\n') + '\n';
}

export function wrapperCmdContent(i: WrapperInput): string {
  const lines = ['@echo off', 'rem ExplainIT checkpoint hook wrapper. Generated by ExplainIT; do not edit (the Doctor rewrites it).'];
  if (i.electron) lines.push('set ELECTRON_RUN_AS_NODE=1');
  // `set "NAME=value"` keeps spaces and special characters in the path intact.
  lines.push(`set "EXPLAINIT_HOME=${i.explainitHome.replace(/"/g, '')}"`);
  lines.push(`${cmdQuote(i.runtime)} ${cmdQuote(i.script)} %*`);
  return lines.join('\r\n') + '\r\n';
}

export const WRAPPER_SH = 'explainit-hook.sh';
export const WRAPPER_CMD = 'explainit-hook.cmd';
export const HOOK_SCRIPT = 'explainit-hook.js';

/** Which wrapper the agent config should call on this platform. */
export function wrapperNameFor(platform: NodeJS.Platform): string {
  return platform === 'win32' ? WRAPPER_CMD : WRAPPER_SH;
}
